### ISSUE TITLE
A $ in service credentials does a BASH variable substitution

### ISSUE THREAD

**Issue by mheath** [cloudfoundry/dea_ng#144]
We have a situation where a user tried to use a password with a $ in it in their user provided service credentials and instead of getting the $ in their VCAP_SERVICES, the $ and everything after it disappeared. I have been able to confirm that a variable substitution is happening in this case.

I have been able to patch it by modifying https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/env/exporter.rb to have the following:

```ruby
        variables.map do |(key, value)|
+          if key == "VCAP_SERVICES" || key == "VCAP_APPLICATION"
+            value = value.to_s.gsub('$', '\$')
+          end
          %Q{export %s="%s";\n} % [key, value.to_s.gsub('"', '\"')]
```

However, I'm not convinced this is the best solution since it doesn't escape everything. (I don't think a back tick '`' will work, for example.)

I singled out VCAP_SERVICES out of concern that some values may want variable substitution but I'm not sure.

Regardless, this is an issue that will likely affect other users.

**Comment by dieucao** [comment]
@mheath This will be fully fixed in the next cf-release, likely v201.

**Comment by mheath** [comment]
Wasn't this fixed in v200? I just merged v200 into our our forked release
and removed the patch I made to the DEA to fix this problem and everything
appears to be working as expected.

**Comment by zaksoup** [comment]
Hi @mheath,

A commit fixing this made it into v200, however our policy is not to officially consider these things fixed until the story is accepted by our PM. The final commit associated with this issue went through our pipeline after v200 and will be released in v201, however the majority of the work did make it into v200. Sorry for the confusion.

Thanks,

@jfmyers9 && @zaksoup, CF Runtime Team

**Comment by dieucao** [comment]
@mheath There was one part that wasn't quite working, which was for DATABASE_URL which gets pulled out of VCAP_SERVICES.  That part of the fix will make it in to v201.

**Comment by mheath** [comment]
Excellent. Thanks for the clarification.

**Comment by xiwenc** [comment]
Is there a reason why the shell escaping is done only for VCAP_SERVICES and VCAP_APPLICATION but not the user-provided environment variables?

${HOME} actually get evaluated during runtime:
```
cf set-env test.domain.tld MY_VAR "\${HOME}"
cf restage test.domain.tld
```
And here we actually receive "${HOME}" as literal:
```
cf set-env test.domain.tld MY_VAR "\\\${HOME}"
cf restage test.domain.tld
```

I understand the former grants some flexibility but it is counterintuitive in my opinion because the user has to escape shell characters themselves.
