### ISSUE TITLE
Dea got "instance.start.failed with error failed to accept connections within health check timeout" while start up python app

### ISSUE THREAD

**Issue by wangping710** [cloudfoundry/dea_ng#162]
dea got "instance.start.failed with error failed to accept connections within health check timeout"  error  while push app on cf cli ,but Enter the /home/vcap directory in container ,  can manually start the app，The related information is as follows：

The startup command in the Procfile file as follows：web: python wsgi.py

Content of manifest.yml:
applications:
- name: python-bottle-cl-14
  memory: 256M
  instances: 1

add debug log code in dea，get  content on start_script as follows：
umask 077\nexport VCAP_APPLICATION=\"{\\\"limits\\\":{\\\"mem\\\":256,\\\"disk\\\":1024,\\\"fds\\\":16384},\\\"application_version\\\":\\\"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233\\\",\\\"application_name\\\":\\\"python-bottle-cl-14\\\",\\\"application_uris\\\":[\\\"python-bottle-cl-14.9.91.18.103.xip.io\\\"],\\\"version\\\":\\\"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233\\\",\\\"name\\\":\\\"python-bottle-cl-14\\\",\\\"space_name\\\":\\\"dev\\\",\\\"space_id\\\":\\\"8cd2a4f8-8e1b-4774-ad5d-5647c01c3647\\\",\\\"uris\\\":[\\\"python-bottle-cl-14.9.91.18.103.xip.io\\\"],\\\"users\\\":null,\\\"application_id\\\":\\\"fb6edef0-6e1e-438f-80c3-eb8c19fe095a\\\",\\\"instance_id\\\":\\\"8f634400658f4970a2d33cfdfa3ff074\\\",\\\"instance_index\\\":0,\\\"host\\\":\\\"0.0.0.0\\\",\\\"port\\\":61015,\\\"started_at\\\":\\\"2015-03-13 10:55:25 +0000\\\",\\\"started_at_timestamp\\\":1426244125,\\\"start\\\":\\\"2015-03-13 10:55:25 +0000\\\",\\\"state_timestamp\\\":1426244125}\";\nexport VCAP_SERVICES=\"{}\";\nexport MEMORY_LIMIT=\"256m\";\nexport HOME=\"$PWD/app\";\nexport TMPDIR=\"$PWD/tmp\";\nexport VCAP_APP_HOST=\"0.0.0.0\";\nexport VCAP_APP_PORT=\"61015\";\nexport PORT=\"$VCAP_APP_PORT\";\n\n\nunset GEM_PATH\nif [ -d app/.profile.d ]; then\n  for i in app/.profile.d/*.sh; do\n    if [ -r $i ]; then\n      . $i\n    fi\n  done\n  unset i\nfi\n\nDROPLET_BASE_DIR=$PWD\ncd app\necho $$ >> $DROPLET_BASE_DIR/run.pid\nexec bash -c python\\ wsgi.py\n",

Below is the DEA log:
{"timestamp":1426244127.5314178,"message":"droplet.healthcheck.port","log_level":"debug","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":256,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":256,"disk":1024,"fds":16384},"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","name":"python-bottle-cl-14","space_name":"dev","space_id":"8cd2a4f8-8e1b-4774-ad5d-5647c01c3647","uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"application_id":"fb6edef0-6e1e-438f-80c3-eb8c19fe095a","droplet_sha1":"9acde13801743edcac14680076f7fd463488a5ce","instance_id":"8f634400658f4970a2d33cfdfa3ff074","private_instance_id":"b7adec50508b461392720f860df2fabfbe386dd47263413c87b7081f23f55669","state":"STARTING","state_timestamp":1426244125.2858455,"state_born_timestamp":1426244125.284365,"state_starting_timestamp":1426244125.2858508,"warden_handle":"18h54ud4o9o","warden_job_id":40},"host":"7.7.7.52","port":61015},"thread_id":9162860,"fiber_id":23163920,"process_id":25923,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":774,"method":"block in promise_port_open"}
{"timestamp":1426244127.5365767,"message":"droplet.warden.link.completed","log_level":"warn","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":256,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":256,"disk":1024,"fds":16384},"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","name":"python-bottle-cl-14","space_name":"dev","space_id":"8cd2a4f8-8e1b-4774-ad5d-5647c01c3647","uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"application_id":"fb6edef0-6e1e-438f-80c3-eb8c19fe095a","droplet_sha1":"9acde13801743edcac14680076f7fd463488a5ce","instance_id":"8f634400658f4970a2d33cfdfa3ff074","private_instance_id":"b7adec50508b461392720f860df2fabfbe386dd47263413c87b7081f23f55669","state":"STARTING","state_timestamp":1426244125.2858455,"state_born_timestamp":1426244125.284365,"state_starting_timestamp":1426244125.2858508,"warden_handle":"18h54ud4o9o","warden_job_id":40},"exit_status":1,"exit_description":"app instance exited"},"thread_id":9162860,"fiber_id":16470300,"process_id":25923,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":732,"method":"block in link"}
{"timestamp":1426244127.5372813,"message":"droplet.unhealthy","log_level":"warn","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":256,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":256,"disk":1024,"fds":16384},"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","name":"python-bottle-cl-14","space_name":"dev","space_id":"8cd2a4f8-8e1b-4774-ad5d-5647c01c3647","uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"application_id":"fb6edef0-6e1e-438f-80c3-eb8c19fe095a","droplet_sha1":"9acde13801743edcac14680076f7fd463488a5ce","instance_id":"8f634400658f4970a2d33cfdfa3ff074","private_instance_id":"b7adec50508b461392720f860df2fabfbe386dd47263413c87b7081f23f55669","state":"CRASHED","state_timestamp":1426244127.5368512,"state_born_timestamp":1426244125.284365,"state_starting_timestamp":1426244125.2858508,"warden_handle":"18h54ud4o9o","warden_job_id":40,"state_crashed_timestamp":1426244127.536857}},"thread_id":9162860,"fiber_id":17694660,"process_id":25923,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":550,"method":"block in start"}
{"timestamp":1426244127.5381448,"message":"instance.start.failed with error failed to accept connections within health check timeout","log_level":"warn","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":256,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":256,"disk":1024,"fds":16384},"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","name":"python-bottle-cl-14","space_name":"dev","space_id":"8cd2a4f8-8e1b-4774-ad5d-5647c01c3647","uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"292e7c2d-67ea-4d06-8d6d-e4ffcf47c233","application_name":"python-bottle-cl-14","application_uris":["python-bottle-cl-14.9.91.18.103.xip.io"],"application_id":"fb6edef0-6e1e-438f-80c3-eb8c19fe095a","droplet_sha1":"9acde13801743edcac14680076f7fd463488a5ce","instance_id":"8f634400658f4970a2d33cfdfa3ff074","private_instance_id":"b7adec50508b461392720f860df2fabfbe386dd47263413c87b7081f23f55669","state":"CRASHED","state_timestamp":1426244127.537521,"state_born_timestamp":1426244125.284365,"state_starting_timestamp":1426244125.2858508,"warden_handle":"18h54ud4o9o","warden_job_id":40,"state_crashed_timestamp":1426244127.5375252},"duration":2.251916435,"error":"failed to accept connections within health check timeout","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/promise.rb:14:in `block in resolve'"]},"thread_id":9162860,"fiber_id":17694860,"process_id":25923,"file":"/var/vcap/packages/dea_next/lib/dea/task.rb","lineno":104,"method":"block in resolve_and_log"}

but i push the app with diego，startup success

why？

**Comment by zaksoup** [comment]
Hi,

The most common reason for this issue is that your app is not listening on the expected port. Apps pushed to CloudFoundry should listen on the port specified by the `$PORT` environment variable.

The common pattern to consume this environment variable is to pass it into the start script for your app as an argument in the Procfile

`web: python wsgi.py $PORT`

Please take a look at our example python app. [1]

[1] https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/python

Please let us know if this solves your issue!
Thanks,
@zaksoup + @jfmyers9, CF Runtime Team

**Comment by wangping710** [comment]
hi，
I push you provide the app, but report the same error.

I useing  cf 195 version

**Comment by zaksoup** [comment]
Can you give us logs from when you pushed the sample app? We do not have enough of the output to find the root issue.

Thanks,
@zaksoup + @DanLavine, CF Runtime Team

**Comment by wangping710** [comment]
is it sucessful while you push the sample app on cf ? what logs ? from dea or other?

**Comment by wangping710** [comment]
dea got logs on the sample app as follows:

{"timestamp":1426674267.7522008,"message":"nats.message.received","log_level":"debug","source":"Dea::Nats","data":{"subject":"dea.0-9cb7552fb7c34294b053a2cb3f2cfe76.start","data":{"droplet":"7587662f-baa6-4c80-8442-77fb04ee17c5","name":"python3","uris":["python3.9.91.34.133.xip.io"],"prod":false,"sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","executableFile":"deprecated","executableUri":"http://upload:c1oudc0w@11.11.12.10:9022/staging/droplets/7587662f-baa6-4c80-8442-77fb04ee17c5/download","version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","services":[],"limits":{"mem":128,"disk":1024,"fds":16384},"env":["http_proxy=http://9.91.13.41:8081","https_proxy=https://9.91.13.41:8081"],"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"index":0,"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}]}},"thread_id":9990140,"fiber_id":18753720,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/nats.rb","lineno":148,"method":"handle_incoming_message"}
{"timestamp":1426674267.7537193,"message":"droplet.starting","log_level":"info","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":128,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"application_id":"7587662f-baa6-4c80-8442-77fb04ee17c5","droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","instance_id":"5a66fda87541495a9408884169fa5771","private_instance_id":"acff208877c146729c2600ce0a472851b80ab3536cb947aba6965e275bd05673","state":"BORN","state_timestamp":1426674267.7527466,"state_born_timestamp":1426674267.7527528}},"thread_id":9990140,"fiber_id":23869640,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":486,"method":"block in start"}
{"timestamp":1426674267.7540698,"message":"New droplet: 64f0c3001762f95443d4bb751ec6e88f5ef54259","log_level":"debug","source":"Dea::DropletRegistry","data":{"droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259"},"thread_id":9990140,"fiber_id":20018980,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/droplet_registry.rb","lineno":14,"method":"block in initialize"}
{"timestamp":1426674268.0021672,"message":"Download succeeded","log_level":"info","source":"Download","data":{},"thread_id":9990140,"fiber_id":18753720,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/utils/download.rb","lineno":60,"method":"block in download!"}
{"timestamp":1426674268.0025957,"message":"droplet.download.succeeded","log_level":"debug","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":128,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"application_id":"7587662f-baa6-4c80-8442-77fb04ee17c5","droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","instance_id":"5a66fda87541495a9408884169fa5771","private_instance_id":"acff208877c146729c2600ce0a472851b80ab3536cb947aba6965e275bd05673","state":"STARTING","state_timestamp":1426674267.7539363,"state_born_timestamp":1426674267.7527528,"state_starting_timestamp":1426674267.7539408},"duration":null,"destination":"/var/vcap/data/dea_next/droplets/64f0c3001762f95443d4bb751ec6e88f5ef54259/droplet.tgz"},"thread_id":9990140,"fiber_id":18753720,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":572,"method":"block (2 levels) in promise_droplet"}
{"timestamp":1426674268.3096988,"message":"setting up egress rules: [{\"destination\"=>\"0.0.0.0-9.255.255.255\", \"protocol\"=>\"all\"}, {\"destination\"=>\"11.0.0.0-169.253.255.255\", \"protocol\"=>\"all\"}, {\"destination\"=>\"169.255.0.0-172.15.255.255\", \"protocol\"=>\"all\"}, {\"destination\"=>\"172.32.0.0-192.167.255.255\", \"protocol\"=>\"all\"}, {\"destination\"=>\"192.169.0.0-255.255.255.255\", \"protocol\"=>\"all\"}, {\"destination\"=>\"0.0.0.0/0\", \"ports\"=>\"53\", \"protocol\"=>\"tcp\"}, {\"destination\"=>\"0.0.0.0/0\", \"ports\"=>\"53\", \"protocol\"=>\"udp\"}]","log_level":"debug","source":"Container","data":{},"thread_id":9990140,"fiber_id":22204120,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/container/container.rb","lineno":130,"method":"setup_egress_rules"}

{"timestamp":1426674309.591418,"message":"droplet.health-check.get-container-info","log_level":"debug","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":128,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"application_id":"7587662f-baa6-4c80-8442-77fb04ee17c5","droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","instance_id":"d4a02bfe57d34dcdaebd2ada3f4a48b6","private_instance_id":"375000fc08ca4c018570e2493210c54230afce33804b41cb8507f1f60be86364","state":"STARTING","state_timestamp":1426674307.7539637,"state_born_timestamp":1426674307.7527323,"state_starting_timestamp":1426674307.7539687,"warden_handle":"18hd7h1jpud","warden_job_id":822}},"thread_id":9990140,"fiber_id":26898800,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":776,"method":"block in promise_health_check"}
{"timestamp":1426674309.6148634,"message":"droplet.health-check.container-info-ok","log_level":"debug","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":128,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"application_id":"7587662f-baa6-4c80-8442-77fb04ee17c5","droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","instance_id":"d4a02bfe57d34dcdaebd2ada3f4a48b6","private_instance_id":"375000fc08ca4c018570e2493210c54230afce33804b41cb8507f1f60be86364","state":"STARTING","state_timestamp":1426674307.7539637,"state_born_timestamp":1426674307.7527323,"state_starting_timestamp":1426674307.7539687,"warden_handle":"18hd7h1jpud","warden_job_id":822}},"thread_id":9990140,"fiber_id":26898800,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":778,"method":"block in promise_health_check"}
{"timestamp":1426674309.6153512,"message":"droplet.healthcheck.port","log_level":"debug","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":128,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"application_id":"7587662f-baa6-4c80-8442-77fb04ee17c5","droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","instance_id":"d4a02bfe57d34dcdaebd2ada3f4a48b6","private_instance_id":"375000fc08ca4c018570e2493210c54230afce33804b41cb8507f1f60be86364","state":"STARTING","state_timestamp":1426674307.7539637,"state_born_timestamp":1426674307.7527323,"state_starting_timestamp":1426674307.7539687,"warden_handle":"18hd7h1jpud","warden_job_id":822},"host":"11.11.12.11","port":61212},"thread_id":9990140,"fiber_id":26982140,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":737,"method":"block in promise_port_open"}
{"timestamp":1426674309.6164336,"message":"droplet.warden.link.completed","log_level":"warn","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":128,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":null,"health_check_timeout":null,"vcap_application":{"limits":{"mem":128,"disk":1024,"fds":16384},"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","name":"python3","space_name":"dev","space_id":"81a4cd0e-8095-473d-a16e-586f2a705419","uris":["python3.9.91.34.133.xip.io"],"users":null},"egress_network_rules":[{"destination":"0.0.0.0-9.255.255.255","protocol":"all"},{"destination":"11.0.0.0-169.253.255.255","protocol":"all"},{"destination":"169.255.0.0-172.15.255.255","protocol":"all"},{"destination":"172.32.0.0-192.167.255.255","protocol":"all"},{"destination":"192.169.0.0-255.255.255.255","protocol":"all"},{"destination":"0.0.0.0/0","ports":"53","protocol":"tcp"},{"destination":"0.0.0.0/0","ports":"53","protocol":"udp"}],"instance_index":0,"application_version":"15cfea4a-8c3c-4b2f-a44c-8975949d6cca","application_name":"python3","application_uris":["python3.9.91.34.133.xip.io"],"application_id":"7587662f-baa6-4c80-8442-77fb04ee17c5","droplet_sha1":"64f0c3001762f95443d4bb751ec6e88f5ef54259","instance_id":"d4a02bfe57d34dcdaebd2ada3f4a48b6","private_instance_id":"375000fc08ca4c018570e2493210c54230afce33804b41cb8507f1f60be86364","state":"STARTING","state_timestamp":1426674307.7539637,"state_born_timestamp":1426674307.7527323,"state_starting_timestamp":1426674307.7539687,"warden_handle":"18hd7h1jpud","warden_job_id":822},"exit_status":1,"exit_description":"app instance exited"},"thread_id":9990140,"fiber_id":26900440,"process_id":25884,"file":"/var/vcap/packages/dea_next/lib/dea/starting/instance.rb","lineno":695,"method":"block in link"}

**Comment by jfmyers9** [comment]
Hi @wangping710,

From what I can tell from the above logs, your application is failing the health check. Thus the DEA does not think that the application has begun accepting connections on the `$PORT` specified in the specified health check timeout. From the information above I have a couple of suggestions and questions about your deployment.

Questions:

- Can you please provide us with the full output to `cf push ...` for the failing application?
- Which version of the python buildpack do you have installed currently? This information can be obtained by running `cf buildpacks`.
- Can you please provide the output of `bosh vms --vitals` so that we can have more information on the vms in your deployment?

Suggestions:

- I noticed that the application name was `python3`. I believe that the fixture python application we linked above does not currently work on python 3. See this [issue](https://github.com/cloudfoundry/cf-acceptance-tests/pull/49) for more information. Thus if you are pushing the application using python3, it may be worth trying python2.7. You can control the version of python that you use for your python application by specifying `python-2.7.9` in `runtime.txt`.
- You may want to try increasing the healthcheck timeout for the DEA. If your DEA is under heavy load there is a chance that the application is unable to start in the timeout specified. By increasing this value, the application may start eventually.

Let me know if any of those suggestions work for you.

Thanks,

@jfmyers9, CF Runtime Team

**Comment by DanLavine** [comment]
Hi @wangping710,

We are going to close this issue because it has been open for a couple of weeks without a response. If you are still experiencing problems please feel free to reopen the issue.

Thanks,
@DanLavine && @utako, The CF Runtime Team
