### ISSUE TITLE
dea heartbeat send before uuid is generated

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/dea_ng#167]
When a DEA starts, it sends out the "dea.heartbeat" message, before the dea uuid is generated.

The send_heartbeat EM interval is setup in https://github.com/cloudfoundry/dea_ng/blob/master/bin/dea#L29, but the dea uuid is generated in https://github.com/cloudfoundry/dea_ng/blob/master/bin/dea#L30.
The field "dea" in "dea.heartbeat" is null (https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/protocol.rb#L25).

What we end up seeing are:
{"timestamp":1436507444.113436222,"process_id":25143,"source":"vcap.hm9000.listener","log_level":"error","message":"Could not put instance heartbeats in store: - Error:node is a directory, not a leaf","data":null}

**Comment by jpalermo** [comment]
Hi @fraenkel,

This should be fixed with this [commit](https://github.com/cloudfoundry/dea_ng/commit/b74390b2472a6a929807040f4439a30ecb46e699).
