### ISSUE TITLE
DEA doesn't properly manage nats server failure

### ISSUE THREAD

**Issue by aalbanes** [cloudfoundry/dea_ng#169]
Hi all, 
I am working on some resiliency test that involve NATS and I am facing a weird issue with DEA upon a specific sequence of NATS crash simulation.

<H3>Environment</H3>
I am using a test cf deployment  and not a DevBox (BoshLite). 
I've a deployment with two NATS servers:  NATS/0 and NATS/1.

<H3>Scenario</H3>
- STEP 1: CF is properly working, I simulate a crash of NATS/0 by stopping the process via monit stop;
- STEP 2: I verify that NATS/1 is being contacted by issuing a tcpdump command
- STEP 3: I start again the NATS/0 instances and stop NATS/1

Upon STEP3 I noticed several failures in DEA and CC.  I run a script that verify DEA connections to nat (it issues  <B>netstat -alep | grep  nat</B> on each DEA) and I didn't find  connections in place.

I gave a look to the code and according to me it seems we have an integration issue among the DEA code:
-https://github.com/cloudfoundry/dea_ng/blob/4b1a50ae5598b0c70cb3e5895ed800e0cff37722/lib/dea/nats.rb#L101-L110

and nats client at (these lines are the same as in gem nats-0.5.0.beta.16)): 
- https://github.com/nats-io/ruby-nats/blob/master/lib/nats/client.rb#L790-L807 

When NATS/0 was stopped on the STEP 1, nats client remove that server from 
server_pool list ,then when NATS/0 is up again, no one re-init this list, dea code doesn't initialize again the client.
At STEP 3 NATS/1 is removed from server_pool list  that remains empty.

To support this conjecture I was not able to find any entry in the DEA logs related to "nats.connecting".

**Comment by Quintaminant** [comment]
Hi @aalbanes,

We've addressed this [here](https://github.com/cloudfoundry/cloud_controller_ng/issues/403) in a similar issue that you opened recently; read details there.

Thanks for opening this issue — apologies to leave you hanging —
@Quintaminant & @rmasand of CF CAPI

**Comment by Amit-PivotalLabs** [comment]
Hi @aalbanes,

Just a follow up to what @Quintaminant and @rmasand said: while we are making larger architectural changes (Diego, Routing API, internal service discovery) to phase out NATS, it will require further investigation to understand the current impact of the issue you raised, and the cost of solving it especially as it pertains to delaying the longer-term solution of phasing NATS out. @fraenkel and @sykesm will investigate further, and open up new Issues/PRs as appropriate.

This comment is cross-posted [here](https://github.com/cloudfoundry/cloud_controller_ng/issues/403#issuecomment-124930568)

Thanks,
Amit, CF Release Integration team
