### ISSUE TITLE
dea_ng varz exposed customer data vulnerable to eavesdropping (plain http protected by basic auth)

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/dea_ng#179]
Most Cf components varz when sanitized to only include non sensitive stats data. Cf
https://www.pivotaltracker.com/story/show/65300526
https://www.pivotaltracker.com/story/show/65042430

However the dea varz still include some sensitive details about containers such as:
- app name
- app routes (uris)
- security groups (egress_network_rules)
- container memory stats

Currently varz are always exposed in plain http, exposing the customer data to eavesdropping risks if intruders are able to sniff traffic to DEA
https://github.com/cloudfoundry/vcap-common/blob/4ae2f57d5a79f80b4d245b87e048f8a37335dab6/lib/vcap/component.rb#L131-L145 

While there are more serious eavesdropping risk in the system (e.g. gorouter to app container traffic is by default plain http), some efforts such as tls to container or [ipsec tunelling between gorouter and deas](http://www.cfsummit.com/sites/cfs2015/files/pages/files/cfsummit15_price.pdf) try to address these risks. It might therefore be interesting to address varz -related risk.

The varz endpoint provides useful diagnostic data used by admin-ui, even though varz is being deprecated in favor or doppler-style metrics. This would be fine if varz could optionally turned off or started on https, and potentially support mutual ssl auth in its yml config (i.e. expect clients to offer SSL cert to connect to).

In terms of implementing secret rotation, it seems that the basic auth (username and password) are automatically generated as hinted into 
https://groups.google.com/a/cloudfoundry.org/forum/#!searchin/vcap-dev/varz/vcap-dev/rycUnc0TS38/FCmgtebOD08J however I could not yet verify this into the code:
- Specs don't describe the password being setteable
https://bosh.io/jobs/dea_next?source=github.com/cloudfoundry/cf-release&version=224
- the yml template does not include status hash
https://github.com/cloudfoundry/cf-release/blob/master/jobs/dea_next/templates/dea.yml.erb
- However dea config confirms status options are optional
https://github.com/cloudfoundry/dea_ng/blob/d710ce11a539293e5cd78231f5722514288530e8/lib/dea/config.rb#L80-L84

So restarting dea should automatically rotate varz basic auth, so no issues there.

**Comment by Amit-PivotalLabs** [comment]
It's worth noting that Collector and /varz are being deprecated: https://github.com/cloudfoundry/collector

**Comment by gberche-orange** [comment]
thanks @Amit-PivotalLabs for the follow up. Refined a bit the issue desc to remind varz deprecation plans. What about conditionally enabling varz to be turned off or start on https during this deprecation phase?

**Comment by Amit-PivotalLabs** [comment]
Hey @gberche-orange 

I know you mentioned the /varz data being useful, but are you saying you'd be okay with a solution that allows just disabling populating this data in /varz altogether?  Given that collector is being deprecated, and indeed the DEAs will eventually give way to Diego, I'm hoping to find the simplest thing that will meet your needs.

**Comment by gberche-orange** [comment]
Thanks Amit. For my particular case, the DEA replacement by Diego are indeed satisfactory (production workloads with security requirements will come after our diego transition). 

Sorry for the noise on this issue. Feel free to close it if there is no other people impacted.

**Comment by Amit-PivotalLabs** [comment]
@gberche-orange great, glad that works for you. Will close out.
