### ISSUE TITLE
Failed to start multiple apps at the same time

### ISSUE THREAD

**Issue by YedengfengPig** [cloudfoundry/dea_ng#180]
I run a local Cloud Foundry instance on VM for studying by cf_nise_installer. If there are two users to start apps at the same time, it fail often. the error message is "failed to accept connections within health check timeout". it seems modifying the startup time doesn't work (cf push ... -t 180). But if starting apps one by one, it success a lot. why?

**Comment by YedengfengPig** [comment]
There is no  memory or port issue.

**Comment by Amit-PivotalLabs** [comment]
Hi @YedengfengPig 

What happens if you just have one app with multiple instances.  If you stop and then start it, do you get the same type of problem?  Trying to figure out if it is an issue with multiple different apps, or simply multiple instances (of same app or different app, shouldn't matter).

**Comment by YedengfengPig** [comment]
hi @Amit-PivotalLabs
It is an issue with multiple instances.
It looks like a single instance can be started by one time.
Is it because I have only one DEA server?

**Comment by Amit-PivotalLabs** [comment]
@YedengfengPig it shouldn't be an issue with having only one DEA server.  A DEA or Diego Cell can handle hundreds of instances, as long as the machine has enough compute resources.  Can you give more details of your deployment?  I don't know much about nise (and you may wish to open an issue against their repo), but maybe you can say what version of cf you're deploying, how it's configured, etc.

**Comment by Amit-PivotalLabs** [comment]
Hi @YedengfengPig any update?

**Comment by YedengfengPig** [comment]
hi @Amit-PivotalLabs  
4 cpus  24G memory 100G disk  ubuntu 14.04

and this is dea.yml:

---
status:
  port: 28888
  user: dea
  pass: "c1oudc0w"

nats_servers:

  - nats://nats:c1oudc0w@10.105.7.156:4222


dea_ruby: /usr/bin/ruby

pid_filename: /var/vcap/sys/run/dea_next/dea_next.pid

base_dir: /var/vcap/data/dea_next

warden_socket: /var/vcap/data/warden/warden.sock

evacuation_bail_out_time_in_seconds: 115
default_health_check_timeout: 60
crash_lifetime_secs: 3600

directory_server:
  protocol: 'https'
  v1_port: 12345
  v2_port: 32766
  file_api_port: 23456
  streaming_timeout: 60
  logging:
    file: /var/vcap/sys/log/dea_next/dir_server.log
    syslog: vcap.directory_server
    level: debug

domain: 10.105.7.156.xip.io

logging:
  file: /var/vcap/sys/log/dea_next/dea_next.log
  level: debug
  syslog: vcap.dea_next

loggregator:
  router: 127.0.0.1:3456
  shared_secret: c1oudc0w


index: 0

intervals:
  heartbeat: 60
  advertise: 5
  router_register_in_seconds: 20

resources:
  memory_mb: 16000
  memory_overcommit_factor: 1
  disk_mb: 32000
  disk_overcommit_factor: 1

staging:
  enabled: true
  max_staging_duration: 900
  memory_limit_mb: 1024
  disk_limit_mb: 6144
  cpu_limit_shares: 512
  disk_inode_limit: 200000

instance:
  memory_to_cpu_share_ratio: 8
  min_cpu_share_limit: 1
  max_cpu_share_limit: 256
  disk_inode_limit: 200000

stacks:
- name: cflinuxfs2
  package_path: /var/vcap/packages/rootfs_cflinuxfs2/rootfs


placement_properties:
  zone: default


cc_url: https://internal_user:c1oudc0w@api.10.105.7.156.xip.io

**Comment by YedengfengPig** [comment]
hi @Amit-PivotalLabs 

cf-cli:
cf version 6.13.0-e68ce0f-2015-10-15T15:53:50+00:00

cf-release :
name: cf
version: '221'

**Comment by fraenkel** [comment]
@YedengfengPig 
In the working case, do you know how long it takes to start and mark your application healthy? You will most likely need to look at the DEA log to determine this.
Give you are using a single VM for all of CF, I am thinking that it is just taking too long to start both containers.

The start timeout on cf push is how long the CLI will wait for the application to start before timing out.

You could adjust the health_check_timeout field on your Application via cf curl to a larger value or adjust the default timeout if this is going to be a common occurrence.

**Comment by YedengfengPig** [comment]
ok thanks
