### ISSUE TITLE
DEA fails to start because Warden is down

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/dea_ng#184]
During a deployment, I have observed the following behavior:

1.) DEA is stopped by Bosh.
2.) It appears to drain OK
3.) When it comes back up, the DEA is failing because it can't talk to Warden.
4.) Warden is flapping.

The control script log repeats this over and over.

```
[2016-01-12 23:34:18+0000] ------------ STARTING warden_ctl at Tue Jan 12 23:34:18 UTC 2016 --------------
[2016-01-12 23:34:18+0000] root/linux/destroy.sh /var/vcap/data/warden/depot/tmp
[2016-01-12 23:34:18+0000] root/linux/destroy.sh /var/vcap/data/warden/depot/19936l1gri3
[2016-01-12 23:34:18+0000] Cannot find device w-19936l1gri3-2
```

From what I can tell, the actual Warden process never starts.  The `warden.log` file has no entries beyond the shutdown messages from #1.

It seems like something didn't clean up properly.  The start script is trying to clean up that one particular directory (see above) and never seems to be able to delete it, since it's repeating over and over.

This is with CF v225 & Diego 0.1441.  The environment is mixed and has both DEAs & Diego cells.

The deployment that was done and what triggered this behavior was to bump the number of etcd and and diego db instances, both from 1 to 3.  There were no changes to the DEAs and no stemcell updates.

I did try to reproduce this in a lab environment, but was unable.  Even with a DEA loaded with apps, I was not able to trigger the behavior.

Running a `bosh recreate` on the DEA after it has this problem resolves it.

Please let me know if there is any additional information that would be helpful to debug this problem.

Thanks!

**Comment by fraenkel** [comment]
This was fixed in v226. You can try fixing the script to get around this issue.
https://github.com/cloudfoundry/warden/commit/634ebb21eb011fda64e53b96d50c4d2f01fc21d8

**Comment by sykesm** [comment]
Closing since this seems to have been resolved in v226. Please reopen if that isn't the case.

Thanks.
