### ISSUE TITLE
when moving an app from DEA to Diego, DEA instances stayed running and routable for hours

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/dea_ng#186]
Tested on superman.cf-app.com, the routing acceptance environment on AWS, deployed from release-candidate of cf-release, and Diego 1455
- on router_z1, watching the /routes endpoint as described on https://github.com/cloudfoundry/gorouter/blob/master/README.md#instrumentation
- pushed an app to an env where Diego is the default
- `cf disable-diego myapp`. See that a backend on DEA is added for the route, and backend on Diego is removed
- `cf enable-diego myapp`. See that a backend on Diego is added, and backend on DEA remains
- by doing this back and forth, you can accumulate backends on DEAs
- I had four backends on DEAs that stuck around for two hours then were cleaned up

I have not been able to reproduce this. Now I'm seeing the DEA backends being cleaned up within a minute or two.

From hm9000_sender.log: https://gist.github.com/shalako/ea27f490ff33a635a56e

**Comment by fraenkel** [comment]
After working with @shalako, we determined the issue was due to HM not being fresh. The behavior seen is expected. Once freshness was achieved, the apps were properly removed.
