### ISSUE TITLE
Missing loggregator tags from dea 

### ISSUE THREAD

**Issue by youreddy** [cloudfoundry/dea_ng#187]
The CAPI team used to track the following tags through the collector: 

`cf.collector.uptime_in_seconds`
`cf.collector.reservable_stagers`
`cf.collector.dea_registry_running`
 
Since the [migration from collector to loggregator](https://github.com/cloudfoundry/dea_ng/commit/a1aa10a887c5facb10270f82bba6214529fcfa3d) we no longer have a way of tracking this info. We would like to be able to continue seeing this information through loggregator.

@youreddy & @jeffpak
CF CAPI Team

**Comment by fraenkel** [comment]
This has been delivered.
