### ISSUE TITLE
Missing Firehose Metrics

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/dea_ng#191]
Formerly, we were using `/varz` to monitor our deployment. Since this is deprecated, we're moving to firehose and aren't find a few metrics. The old `/varz` endpoint:
```
{
  "type": "DEA",
  "index": 1,
  "available_memory_ratio": 0.9895089285714286,
  "available_disk_ratio": 0.989,
  "uptime": "27d:18h:51m:12s",
  "cpu": 0.0,
  "cpu_load_avg": 0.22,
  "mem_bytes": 155037696,
  "mem_used_bytes": 3640774656,
  "mem_free_bytes": 13186523136,
  "warden_error_response_count": 1178
  "reservable_stagers": 277,

  ...

}
```

`cpu_load_avg` and `available_memory_ratio` are two useful stats that came back from that endpoint that aren't coming in on the firehose. We used these numbers to decide to scale out and alert based on the numbers passing thresholds.

**Comment by cholick** [comment]
I'm not seeing an equivalent to `reservable_stagers` either

**Comment by cholick** [comment]
This is the commit that removed those metrics:

https://github.com/cloudfoundry/dea_ng/commit/a1aa10a887c5facb10270f82bba6214529fcfa3d#diff-0722211fffee546af0495c5a27cca454L459

**Comment by fraenkel** [comment]
reservable_stagers was added but we haven't released the code that has it.
The next bump will have it. See 9bbacf87955406283c57aa737267fdbdd2f9f098

**Comment by fraenkel** [comment]
I am curious while we don't expose available_memory_ratio, we do expose remaining_memory and remaining_disk. In some cases that is more useful since you know an absolute value and if you have the same amount of starting memory/disk, you can compute the ratio yourself.

Let me know if that is sufficient or you would prefer the ratio value.

**Comment by cholick** [comment]
@fraenkel You question definitely makes sense, and `remaining_memory` is the most useful number; it's what we'll run with for now and change our alerting to trigger off of.

In terms of the `absolute` value, getting that too is useful because the value varies across our environments and has also changed as we resize things. Having a `ratio` or `absolute` total in the broadcast meant that our time series data could remain completely ignorant of the manifests driving our install or having a manual process where we input the current `absolute` numbers: we could have our notifications let us know when a fraction of the runners passed 90% memory usage, things along those lines.

It's not critical or anything, just useful, especially in the context of the monitoring and alerting we've already built. We're migrating to diego, so if you don't think others would fine it useful I'd say skip.

**Comment by fraenkel** [comment]
@cholick I was debating whether to add back the ratio or add the total number so the ratio could be computed since I had a feeling folks might have different values.

**Comment by fraenkel** [comment]
This has been delivered.
