### ISSUE TITLE
Buildpack's release method called twice

### ISSUE THREAD

**Issue by caijj** [cloudfoundry/dea_ng#192]
With the [1] change, the bin/release method of a buildpack is called twice during staging. That's because start_command() and effective_procfile() both end up invoking the installer.release_info(). The duplicate invocation of "release" may result in some unexpected behavior in certain buildpacks. 

[1]: https://github.com/cloudfoundry/dea_ng/commit/166e64f0d6ee7e64641c0198a2726d3414a8ccbf

**Comment by fraenkel** [comment]
This has been delivered.
