### ISSUE TITLE
 ERR Error uploading: (Upload failed - status 0; error: unable to resolve server address

### ISSUE THREAD

**Issue by WenXiuchun** [cloudfoundry/dea_ng#193]
2016-04-19T19:28:26.43+0800 [STG/0]      OUT -----> Uploading droplet (7.0M)
2016-04-19T19:28:26.63+0800 [API/0]      ERR encountered error: Staging error: failed to stage application:
2016-04-19T19:28:26.63+0800 [API/0]      ERR Error uploading: (Upload failed - status 0; error: unable to resolve server address)
2016-04-19T20:12:19.87+0800 [API/0]      OUT Updated app with guid 0ab163f4-1a0f-4dd5-b5e7-60da80ee979c ({"state"=>"STOPPED"})
2016-04-19T20:12:23.24+0800 [DEA/0]      OUT Got staging request for app with id 0ab163f4-1a0f-4dd5-b5e7-60da80ee979c
2016-04-19T20:12:24.30+0800 [API/0]      OUT Updated app with guid 0ab163f4-1a0f-4dd5-b5e7-60da80ee979c ({"state"=>"STARTED"})
2016-04-19T20:12:24.63+0800 [STG/0]      OUT -----> Downloaded app package (4.8M)
2016-04-19T20:12:24.90+0800 [STG/0]      OUT -------> Buildpack version 1.3.6
2016-04-19T20:12:25.01+0800 [STG/0]      OUT Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/16126117-44a0-40ac-bfe1-a18db7ac4924_6f22ffc14ffd6d728d0c793400b1cf3079abba74/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_nginx_nginx-1.9.14-linux-x64.tgz]
2016-04-19T20:12:25.01+0800 [STG/0]      ERR grep: Staticfile: No such file or directory
2016-04-19T20:12:25.01+0800 [STG/0]      OUT -----> Using root folder
2016-04-19T20:12:25.01+0800 [STG/0]      OUT -----> Copying project files into public/
2016-04-19T20:12:25.01+0800 [STG/0]      OUT -----> Setting up nginx
2016-04-19T20:12:25.08+0800 [STG/0]      ERR grep: Staticfile: No such file or directory
2016-04-19T20:12:25.08+0800 [STG/0]      ERR grep: Staticfile: No such file or directory
2016-04-19T20:12:26.66+0800 [STG/0]      OUT -----> Uploading droplet (7.0M)
2016-04-19T20:12:26.80+0800 [API/0]      ERR encountered error: Staging error: failed to stage application:
2016-04-19T20:12:26.80+0800 [API/0]      ERR Error uploading: (Upload failed - status 0; error: unable to resolve server address)

**Comment by WenXiuchun** [comment]
I installed the newest cloud foundry, but I cant start app

**Comment by WenXiuchun** [comment]
this is log of cloud_controller_ng.log

cloud_controller_ng/cloud_controller_ng.log:{"timestamp":1461064774.1477232,"message":"Request failed: 400: {\"code\"=>170001, \"description\"=>\"Staging error: failed to stage application:\\nError downloading: Response status: unknown, Error: unable to resolve server address\\n\", \"error_code\"=>\"CF-StagingError\", \"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb:110:in `check_staging_error!'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb:73:in `handle_first_response'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/dea/app_stager_task.rb:47:in `block (2 levels) in stage'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:48:in `call'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:48:in `trigger_on_response'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:43:in `handle_received_response'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/multi_response_message_bus_request.rb:22:in `block in request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:88:in `yield'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:88:in `run_handler'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:41:in `block (2 levels) in request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:104:in `yield'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:104:in `process_message'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/cf-message-bus-0.3.4/lib/cf_message_bus/message_bus.rb:40:in `block in request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:424:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:424:in `block in request'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:524:in `call'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:524:in `on_msg'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/cache/ruby-nats-8571cf9d685b/lib/nats/client.rb:585:in `receive_data'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'\", \"/var/vcap/data/packages/cloud_controller_ng/469145d8fb043950582100c0c1a179c756fcff1f/cloud_controller_ng/lib/cloud_controller/runner.rb:87:in `run!'\", \"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/bin/cloud_controller:8:in `<main>'\"]}","log_level":"info","source":"cc.api","data":{"request_guid":"74a6cbf6-b194-40e8-9569-596a8853f8cb"},"thread_id":70323918593780,"fiber_id":70323911666380,"process_id":2820,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sinatra/vcap.rb","lineno":51,"method":"block in registered"}

**Comment by WenXiuchun** [comment]
this is log of dea_nex.log:

dea_next/dea_next.log:{"timestamp":1461067946.7831073,"message":"staging.task.upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"0ab163f4-1a0f-4dd5-b5e7-60da80ee979c","task_id":"8d25d679fb3c495d8221880e179ad2d2","error":"Error uploading: (Upload failed - status 0; error: unable to resolve server address)","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:605:in `resolve_staging_upload'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:64:in `block in start'","/var/vcap/packages/dea_next/lib/dea/promise.rb:20:in `block in resolve'"]},"thread_id":69818145257880,"fiber_id":69818153154500,"process_id":3671,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":66,"method":"rescue in block in start"}

**Comment by ScarletTanager** [comment]
@WenXiuchun - from your `dea_next.log`, there should be a line shortly before the ones you posted with the message 'staging.task.droplet-upload-failed' OR 'staging.task.buildpack-cache-upload-failed' - can you please paste that section of the `dea_next.log` here?  It will show the destination host which the DEA failed to resolve.

**Comment by WenXiuchun** [comment]
@ScarletTanager 

dea_next.log:{"timestamp":1461067946.7829459,"message":"staging.task.droplet-upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"0ab163f4-1a0f-4dd5-b5e7-60da80ee979c","task_id":"8d25d679fb3c495d8221880e179ad2d2","duration":null,"destination":"http://uploaduser:c1oudc0w@cloud-controller-ng.service.cf.internal:9022/staging/droplets/0ab163f4-1a0f-4dd5-b5e7-60da80ee979c/upload","error":"Error uploading: (Upload failed - status 0; error: unable to resolve server address)","backtrace":null},"thread_id":69818145257880,"fiber_id":69818159412460,"process_id":3671,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":346,"method":"block (2 levels) in promise_app_upload"}


dea_next.log:{"timestamp":1461065006.7118707,"message":"staging.task.buildpack-cache-upload-failed","log_level":"info","source":"Staging","data":{"app_guid":"0ab163f4-1a0f-4dd5-b5e7-60da80ee979c","task_id":"d140e64dc5914893b0ac3c6ca93a1b15","duration":null,"destination":"http://uploaduser:c1oudc0w@cloud-controller-ng.service.cf.internal:9022/staging/buildpack_cache/0ab163f4-1a0f-4dd5-b5e7-60da80ee979c/upload","error":"Error uploading: (Upload failed - status 0; error: unable to resolve server address)","backtrace":null},"thread_id":69818145257880,"fiber_id":69818159412460,"process_id":3671,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":366,"method":"block (2 levels) in promise_buildpack_cache_upload"}

**Comment by WenXiuchun** [comment]
@ScarletTanager 


dea_next.log:{"timestamp":1461110080.5128732,"message":"em-http-request.errored","log_level":"error","source":"AdminBuildpackDownloader","data":{"error":"Error downloading: Response status: unknown, Error: unable to resolve server address","data":{"droplet_uri":"http://uploaduser:c1oudc0w@cloud-controller-ng.service.cf.internal:9022/v2/buildpacks/a32014c0-92ac-49f4-8208-df4358a9fd99/download"}},"thread_id":70329384196500,"fiber_id":70329398544480,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/utils/download.rb","lineno":43,"method":"block in download!"}
dea_next.log:{"timestamp":1461110086.5842893,"message":"em-http-request.errored","log_level":"error","source":"AdminBuildpackDownloader","data":{"error":"Error downloading: Response status: unknown, Error: unable to resolve server address","data":{"droplet_uri":"http://uploaduser:c1oudc0w@cloud-controller-ng.service.cf.internal:9022/v2/buildpacks/23d99fc3-f656-4304-96c0-e0c710ba4988/download"}},"thread_id":70329384196500,"fiber_id":70329398544480,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/utils/download.rb","lineno":43,"method":"block in download!"}
dea_next.log:{"timestamp":1461110218.6218815,"message":"em-http-request.errored","log_level":"error","source":"Staging","data":{"app_guid":"ea71895e-d314-4475-acdb-5ee1d7b3faf9","task_id":"97e3975485dd42f6a4944b5e0fcee0af","error":"Error downloading: Response status: unknown, Error: unable to resolve server address","data":{"droplet_uri":"http://uploaduser:c1oudc0w@cloud-controller-ng.service.cf.internal:9022/staging/apps/ea71895e-d314-4475-acdb-5ee1d7b3faf9"}},"thread_id":70329384196500,"fiber_id":70329398544480,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/utils/download.rb","lineno":43,"method":"block in download!"}
dea_next.log:{"timestamp":1461110218.622064,"message":"staging.app-download.failed","log_level":"debug","source":"Staging","data":{"app_guid":"ea71895e-d314-4475-acdb-5ee1d7b3faf9","task_id":"97e3975485dd42f6a4944b5e0fcee0af","duration":null,"error":"Error downloading: Response status: unknown, Error: unable to resolve server address","backtrace":null},"thread_id":70329384196500,"fiber_id":70329398544480,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":312,"method":"block (2 levels) in promise_app_download"}
dea_next.log:{"timestamp":1461110218.622346,"message":"staging.task.failed","log_level":"info","source":"Staging","data":{"app_guid":"ea71895e-d314-4475-acdb-5ee1d7b3faf9","task_id":"97e3975485dd42f6a4944b5e0fcee0af","error":"Error downloading: Response status: unknown, Error: unable to resolve server address","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/promise.rb:31:in `each'","/var/vcap/packages/dea_next/lib/dea/promise.rb:31:in `run_in_parallel'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:570:in `resolve_staging_setup'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:49:in `block in start'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `call'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `block in run'"]},"thread_id":70329384196500,"fiber_id":70329392507580,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":57,"method":"block in start"}
dea_next.log:{"timestamp":1461110293.8070998,"message":"em-http-request.errored","log_level":"error","source":"Staging","data":{"app_guid":"ea71895e-d314-4475-acdb-5ee1d7b3faf9","task_id":"a4da36b0e4474c3691167338789ba1aa","error":"Error downloading: Response status: unknown, Error: unable to resolve server address","data":{"droplet_uri":"http://uploaduser:c1oudc0w@cloud-controller-ng.service.cf.internal:9022/staging/apps/ea71895e-d314-4475-acdb-5ee1d7b3faf9"}},"thread_id":70329384196500,"fiber_id":70329398544480,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/utils/download.rb","lineno":43,"method":"block in download!"}
dea_next.log:{"timestamp":1461110293.8072608,"message":"staging.app-download.failed","log_level":"debug","source":"Staging","data":{"app_guid":"ea71895e-d314-4475-acdb-5ee1d7b3faf9","task_id":"a4da36b0e4474c3691167338789ba1aa","duration":null,"error":"Error downloading: Response status: unknown, Error: unable to resolve server address","backtrace":null},"thread_id":70329384196500,"fiber_id":70329398544480,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":312,"method":"block (2 levels) in promise_app_download"}
dea_next.log:{"timestamp":1461110293.8075962,"message":"staging.task.failed","log_level":"info","source":"Staging","data":{"app_guid":"ea71895e-d314-4475-acdb-5ee1d7b3faf9","task_id":"a4da36b0e4474c3691167338789ba1aa","error":"Error downloading: Response status: unknown, Error: unable to resolve server address","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/promise.rb:31:in `each'","/var/vcap/packages/dea_next/lib/dea/promise.rb:31:in `run_in_parallel'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:570:in `resolve_staging_setup'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:49:in `block in start'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `call'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `block in run'"]},"thread_id":70329384196500,"fiber_id":70329394865320,"process_id":4348,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":57,"method":"block in start"}

**Comment by ScarletTanager** [comment]
@WenXiuchun - the destination URLs are all correct, so that's not the issue.  I would see if name resolution is working for you generally by doing the following:

1. `bosh ssh runner_z1`
2. dig @127.0.0.1 cloud-controller-ng.service.cf.internal

You should get a valid A record back, in a default bosh-lite config it will be this:
`cloud-controller-ng.service.cf.internal. 0 IN A	10.244.0.138`

Check that you can (also from the `runner` VM) resolve other names, e.g. `google.com`.  If either of these fail, check that the `consul_agent` is running with `monit summary` (you will likely need to be root for this), here is the output from a standard bosh-lite runner VM:

```
Process 'consul_agent'              running
Process 'warden'                    running
Process 'dea_next'                  running
Process 'dir_server'                running
Process 'dea_logging_agent'         running
Process 'metron_agent'              running
```

If `consul_agent` is running (`consul` handles local DNS in a bosh-lite deployment), check that it is listening on the correct port (you will need to be root) with `lsof -i udp:53`, which should give you output like:
```
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
consul  2947 vcap    9u  IPv4  97337      0t0  UDP localhost:domain
```

If `consul_agent` is not running, try `monit start consul_agent` or `monit restart consul_agent` - you can use `monit summary` to check progress.  If it fails to start, check the files `/var/vcap/sys/log/consul_agent/consul_agent.stderr.log` and `consul_agent.stdout.log` (same directory) to see why.

If all else fails, a redeploy should fix the issue.

-@ScarletTanager & @jberkhahn CF RuntimeOG team

**Comment by fraenkel** [comment]
Closing due to lack of response. If you have found additional information, please provide it and re-open the issue.
