### ISSUE TITLE
Provide CPU percentage for container metric

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/dea_ng#194]
Love that DEAs send container metrics.  However, it appears that DEA doesn't send a percentage for `cpuPercentage`.  Diego doesn't send a real percentage either but they do send an aggregate percentage per core.

Max value in Diego is 100 * Cores

Max value in DEA is 1 * Cores

At the very least I'd like Diego and DEA to send comparable values.

Mike

**Comment by fraenkel** [comment]
Actually it does/will. The DEA will send avg_cpu_load. See https://github.com/cloudfoundry/dea_ng/commit/48c96a514b4814047e4b22144d177e738d33c76c

I struggle with that value since you don't know the max amount of CPU nor the available CPU. But I guess it's a question of what you plan to do with the data.

**Comment by youngm** [comment]
@fraenkel Great!  Just to clarify, I'm on cf-release 234 now and get DEA container metrics.  How does https://github.com/cloudfoundry/dea_ng/commit/48c96a514b4814047e4b22144d177e738d33c76c change the metrics?  My hope with this issue is to change DEA so it emits a value for cpuPercentage that I can log and compare against what Diego sends.

If I have 8 CPUs all at 50% load Diego will give a value of 400.  Will https://github.com/cloudfoundry/dea_ng/commit/48c96a514b4814047e4b22144d177e738d33c76c make it so the container metric shows 400.00 like Diego today or will the value be 4.0000 like it is today in 234?

**Comment by fraenkel** [comment]
So we are talking about different things.
The commit delivers avg_load of the host.
The DEA computes the cpu percentage for each container, whereas Garden provides the usage from the cgroup.

**Comment by youngm** [comment]
@fraenkel Got it.  So, yes I'm referring to the loggregator container metric sent for each container.  Would it be possible to simply multiple the value DEA provides for `cpuPercentage` by 100 so the number is closer in value to what the rep reports from Garden?  Or is it not that simple?

**Comment by fraenkel** [comment]
It should be similar, they multiply by 100, however we both have different issues in our math that affect the accuracy, i.e., how we determine the time span between data collection.
We can easily multiply by 100 but we would need to know if that will break anyone.

**Comment by youngm** [comment]
@fraenkel Great.  I think it would be useful if the numbers were somewhat similar.  It would make my monitoring much simpler anyway.

Hopefully the DEA publishing container metrics is new enough of a feature that it won't break too many people.

**Comment by fraenkel** [comment]
Fixed in the next release.
