### ISSUE TITLE
The EvacuationHandler doesn't have the correct locator_responders

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/dea_ng#201]
The DEA startup codes: https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/bootstrap.rb#L351-L360 as below:
    def start
      setup_signal_handlers
      download_buildpacks
      snapshot.load
      start_nats
      setup_sweepers
      start_nats_staging_request_handler

the EvacuationHandler is initialized in method setup_signal_handlers, but the @responders is initialized in method start_nats_staging_request_handler, so that the EvacuationHandler doesn't have the correct locator_responders, when DEA drain process starts, the EvacuationHandler could not stop the DEA heartbeat timer, that causes CloudController still send staging requests to this DEA which is in drain phase.

**Comment by fraenkel** [comment]
https://github.com/cloudfoundry/dea_ng/commit/c8d1f7a622a4b856c040f92fc721cfd02214f452
