### ISSUE TITLE
Routes are not removed when DEA is evacuated

### ISSUE THREAD

**Issue by giner** [cloudfoundry/dea_ng#202]
It often happens that routing records are not deleted while DEA is evacuated and disappear only within [120-150 seconds](https://github.com/cloudfoundry-incubator/routing-release/blob/f84929656d83c63cd6e1c42f3a61b57e237c3c29/jobs/gorouter/templates/gorouter.yml.erb#L41-L42). This causes problems for POST requests ([gorouter returns 502](https://github.com/cloudfoundry/gorouter/issues/130)) for cf-release prior to v237.

How to reproduce:
1. Run a loop to check a particular route every second from gorouter
```
while true; do date; curl http://router-status:PASS@10.1.1.1:8080/routes 2>/dev/null | jq '.["myapp.example.net"]'; sleep 1; echo; done
```
```
Mon Dec 26 08:05:50 UTC 2016
[
  {
    "address": "100.2.1.1:61182",
    "ttl": 0
  }
]

...
```
2. Evacuate a DEA running one of instances associated with the 'myapp.example.net' by `bosh stop dea/0`

When the instance stops and starts on another dea the routing record for this instance disappears immediately however in a few seconds it comes back and disappears later within timeout mentioned above:
```
Mon Dec 26 08:05:51 UTC 2016
[
  {
    "address": "100.2.1.2:61155",
    "ttl": 0
  },
  {
    "address": "100.2.1.1:61182",
    "ttl": 0
  }
]
```

It seems to be happening here: https://github.com/cloudfoundry/dea_ng/blob/c8d1f7a622a4b856c040f92fc721cfd02214f452/lib/dea/bootstrap.rb#L404
Why does it try to register routes while evacuating?

**Comment by fraenkel** [comment]
Please use a more current release. Many of these issues have been fixed. The gorouter has also been fixed to retry when connects fail which should also occur.

**Comment by giner** [comment]
I know about gorouter issue being fixed (and mentioned it above) but I did not manage to find anything about fixing the original issue. The related code has not being changed. This link points to the latest commit of dea_ng, there are: https://github.com/cloudfoundry/dea_ng/blob/c8d1f7a622a4b856c040f92fc721cfd02214f452/lib/dea/bootstrap.rb#L404

**Comment by fraenkel** [comment]
The evacuating instance lives until the DEA is told the new instance is running on another DEA. The instance is removed at this point.

**Comment by giner** [comment]
> The evacuating instance lives until the DEA is told the new instance is running on another DEA. The instance is removed at this point.

This is how it should work however it works differently. The new instance starts and receives traffic. The old instance is already deleted (moreover DEA itself is already stopped completely) however routing table on gorouter still has both old and new records which should not be.

**Comment by giner** [comment]
This does never happens if I change code like this:
```
--- /var/vcap/data/packages/dea_next/lib/dea/bootstrap.rb.orig      2016-03-16 16:33:20.000000000 +0000
+++ /var/vcap/data/packages/dea_next/lib/dea/bootstrap.rb   2016-12-26 14:06:27.223234727 +0000
@@ -363,7 +363,7 @@
 
     def register_routes
       instance_registry.each do |instance|
-        next if !(instance.running? || instance.evacuating?) || instance.application_uris.empty?
+        next if !instance.running? || instance.application_uris.empty?
         router_client.register_instance(instance)
       end
```
Any good reason to register routes while evacuating? It looks like a mistake.
