### ISSUE TITLE
DEA generates logs without timestamps

### ISSUE THREAD

**Issue by giner** [cloudfoundry/dea_ng#204]
loggregator_emitter does not add timestamp to envelop:
```
{
  "origin": "DEA",
  "eventType": 5,
  "deployment": "openstack",
  "job": "dea_z3",
  "index": "1",
  "ip": "100.10.10.10",
  "logMessage": {
    "message": "U3RhcnRpbmcgYXBwIGluc3RhbmNlIChpbmRleCAwKSB3aXRoIGd1aWQgMDBjMjM0NDgtOTBhMS00MjY5LWJlMzMtZTE5N2MyZDM1YmMx",
    "message_type": 1,
    "timestamp": 1476425410317200400,
    "app_id": "00c23448-90a1-4269-be33-e197c2d35bc1",
    "source_type": "DEA",
    "source_instance": "1"
  }
}
```

loggregator_emitter 5.2.0 contains the fix: https://github.com/cloudfoundry/loggregator_emitter/commit/33fbb014385dd1db417b5f22354b0a095e9e1e08

**Comment by fraenkel** [comment]
The commit dea_ng is using includes that commit. Which means the problem is elsewhere.

**Comment by giner** [comment]
> The commit dea_ng is using includes that commit. Which means the problem is elsewhere.

You are right. Overlooked.

**Comment by giner** [comment]
Sorry, I messed up. Please close the issue. It was fixed in v232 for DEA and in v250 for Cloud Controller.

At the time of investigation I found both Cloud Controller and DEA logs without timestamps however I didn't notice that DEA ones were not recent.
