### ISSUE TITLE
Unable to push application with large filenames

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/dea_ng#63]
When I push this demo application [1] to my internal deploy of CF.  I get the log errors in the dea_ng logs like this:

```
 unzip -q /var/vcap/data/dea_next/staging/d20130927-1899-2yld04/app.zip -d /tmp/unstaged\n" exited with status 50 with data {:script=>"          package_size=`du -h /var/vcap/data/dea_next/staging/d20130927-1899-2yld04/app.zip | cut -f1`\n          echo \"-----> Downloaded app package ($package_size)\" >> /tmp/staged/logs/staging_task.log\n          unzip -q /var/vcap/data/dea_next/staging/d20130927-1899-2yld04/app.zip -d /tmp/unstaged\n", :exit_status=>50, :stdout=>"", :stderr=>"error:  cannot create /tmp/unstaged/shapeless/TupleTypeableInstances$$anon$3$$anonfun$cast$20$$anonfun$apply$172$$anonfun$apply$173$$anonfun$apply$174$$anonfun$apply$175$$anonfun$apply$176$$anonfun$apply$177$$anonfun$apply$178$$anonfun$apply$179$$anonfun$apply$180$$anonfun$apply$181.class\n        File name too long\nerror:  cannot create /tmp/unstaged/shapeless/TupleTypeableInstances$$anon$2$$anonfun$cast$21$$anonfun$apply$191$$anonfun$apply$192$$anonfun$apply$193$$anonfun$apply$194$$anonfun$apply$195$$anonfun$apply$196$$anonfun$apply$197$$anonfun$apply$198$$anonfun$apply$199$$anonfun$apply$200.class\n        File name too long\nerror:  cannot create /tmp/unstaged/shapeless/TupleTypeableInstances$$anon$1$$anonfun$cast$22$$anonfun$apply$$$$68562c231eb5e5d094369c6a29a33914$$$$y$223$$anonfun$apply$224$$anonfun$apply$225$$anonfun$apply$226$$anonfun$apply$227$$anonfun$apply$228$$anonfun$apply$229$$anonfun$apply$230.class\n
```

I can unzip the application just fine in my DEA.  Perhaps these is something different in a Warden container?

It attempted to duplicate the issue on run.pivotal.io but was unable to push my application with this error:

```
cf push --path cf-scala-spray_2.10.2-0.1.0-SNAPSHOT.jar
Name> test

Save configuration?> n

Uploading test... FAILED
Upload failed. Try again with 'cf push'.
PUT https://api.run.pivotal.io/v2/apps/8b3db470-7a51-40c2-aa01-e0a4c8015c18/bits timed out
```

So, I haven't verified the issue fully on run.pivotal.io

We are running on stemcell 0.8.0.

Mike

[1] https://docs.google.com/file/d/0ByIViWrm6MZEcTNqRmtOWktpblU/edit?usp=sharing

**Comment by kevinmeredith** [comment]
Does this ticket's closure indicate that the root problem is fixed?

**Comment by eduardohl** [comment]
Well, I'm having the same problem here. Is there anywhere I can get some documentation to solve it? Tried the option in the mail list, but not much success so far.

**Comment by youngm** [comment]
@eduardohl @kevinmeredith In the case of the scala app we just stopped trying.  It was just someone doing a quick test so it wasn't something we had to solve.  Figured if we needed to we could find the scala option for smaller file names but never did.  Sorry.

**Comment by ematpl** [comment]
On most Linux filesystems, there's a maximum file length limit of 255 characters, and on the aufs filesystem that warden and garden-linux both use for their container filesystems, that limit is 242 characters (see http://aufs.sourceforge.net/aufs3/man.html, search for "242"). @youngm, that filename you posted about on vcap-dev is 243 characters, so just over the aufs limit!

Thanks,
Eric

**Comment by eduardohl** [comment]
I guess this is a still unsolved issue, both for CF Garden and Docker. I see three main solutions:
1) recompiling the code, and faulty libs with the scalacOption for limiting file names (unsustainable because of the libs)
2) not using Garden (not sure if this is actually possible)
3) putting the jars directly into the project and running with java -cp (providing each lib) instead of a fat jar

I ended up using a 4th approach for now, which is to use heroku-buildpack-scala. Problem is it compiles everytime I deploy, this being a bad practice as I'm deploying untested artifacts and taking lots of time.

**Comment by ematpl** [comment]
The Garden team's new rootfs wing (https://www.pivotaltracker.com/n/projects/1661239) is also looking at the feasibility of a return to btrfs for the overlay filesystem used in Garden containers, pending validation of its improved stability in Linux kernel versions 4.4 and later. That filesystem has, like many other common filesystems on Linux, a 255-byte limit on its filenames, which I presume would work for those Scala libraries if they're to run on Linux at all.

**Comment by youngm** [comment]
@ematpl That would be awesome!  Thanks for the update.

**Comment by sparameswaran** [comment]
Use Java classpath manifest to specify the additional classes bundled within other jars and then push the main app. instead of having everything packaged as one big jar file. Final structure should be One top Jar file containing multiple internal jars all referred by main classpath manifest entry.

**Comment by eduardohl** [comment]
@ematpl That's amazing, I haven't seen this even in Docker containers. I see the work can be followed up on the tracker you sent, but is there anywhere else I'd find documentation or could track the development besides on the CF GrootFS tracker? Also, would this be available in the standard Cloud Foundry default stack cflinuxfs2 or would it be available on another custom one?

**Comment by ematpl** [comment]
Hey, @eduardohl, your experience would depend on the FS driver that particular instance of the Docker daemon is using to make its containers. If it's using btrfs, vfs, overlay, xfs, etc., you probably wouldn't have encountered it. 

The FS driver that Garden-Linux uses is independent of the stack contents, so if the Garden team switches back to btrfs in some later version it would just start working on those future versions of Garden.

@goonzoid is PMing that team, so he may be able to direct you to some more details about the roadmap. The tracker's probably the best place to monitor progress, though.

Thanks,
Eric

**Comment by eduardohl** [comment]
Thanks for the prompt and complete reply!

**Comment by eduardohl** [comment]
Just in case this might still help anyone, we've managed to use a solution with sbt-native-packager instead of sbt-assembly.

Using sbt-native-packager and the universal:packageBin command a zip can be produced, containing the same contents produced by sbt stage. The jars are kept separate (not-exploded) and avoid the compilation problem generated by the size of files caused by sbt-assembly. After that the java_buildpack is capable of running the app without issues:

cf push sample-app -p ./target/universal/stage -b java_buildpack --health-check-type=none
or 
cf push sample-app -p ./target/universal/sample-app-201608160251.zip -b java_buildpack --health-check-type=none
